### ISSUE TITLE
Stacked borrow violation reported by miri

### ISSUE THREAD

**Issue by Voultapher** [JakubValtar/radsort#1]
Hi, I've recently been doing research on sort implementations and noticed that radsort exhibits stacked borrow violations when sorting random inputs. It should be relatively easy to reproduce by sorting a random set of numbers using miri. If you want you can reuse my project to reproduce it, https://github.com/Voultapher/sort-research-rs change the the test_sort line in tests/main.rs to `use sort_comp::other::rust_radsort as test_sort;` and run it with `MIRIFLAGS='-Zmiri-permissive-provenance' cargo +nightly miri t --features=bevy_radsort -- --exact random`.

**Comment by JakubValtar** [comment]
Thanks for the report! I was able to reproduce by running the radsort test suite in miri.

I'm going to take a look how I can fix it.

**Comment by JakubValtar** [comment]
Fixed in d640025871842d215580e1dd5e7bdebdc6baa5f9

**Comment by lincot** [comment]
@JakubValtar could you publish a new release with the fix to the registry?

**Comment by JakubValtar** [comment]
@lincot I'm investigating a performance regression, but aiming to publish a new version soon.
